### ISSUE TITLE
Accessibility: List of accessibility tasks to break out

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1539]
**Description**
This is a list of some accessibility tasks we should probably do to increase the level of accessibility in the components. This issue will be broke down in separate task before completing this issue can be considered done when all are checked off and all sub issues are created.

**List of Some Tasks**

- [x] Test new color palette and get it installed.
- [x] ~~Set and list supported screen readers and versions and supported guidelines (WCAG21 and VPAT 2.2). Moved to https://github.com/infor-design/enterprise/issues/1722~~
- [x] Review Amp output for any unsolved issues https://amp.levelaccess.net (list in future)
- [x] Test against the newer https://www.w3.org/TR/WCAG21/ spec for any changes
- [x] Fix all open accessibility issues https://github.com/infor-design/enterprise/issues?q=is%3Aissue+is%3Aopen+label%3A%22focus%3A+accessibility%22+
- [x] Review comments in GHR VPATS and make more issues
- [x] Make datagrid work with screen reader
- [x] Retest menu button on Jaws - arrow keys not working
- [x] Test Completion-chart with jaws and general accessibility (Added https://github.com/infor-design/enterprise/issues/4377)
- [x] Make sure everything runs axe tests - in new project
- [x] Test Field options with jaws and general accessibility (Added https://github.com/infor-design/enterprise/issues/4407)
- [x] Test Empty message options with jaws and general accessibility
- [x] Better document how screen readers work with each component and what developers need to know.
- [x] ~~Document what we aim to do and dont do. i.e. we add `aria` attributes automatically where appropriate, we provide a compliant series of color schemes, we provide audio-backups for written text where possible: Moved to https://github.com/infor-design/enterprise/issues/1540~~
- [x] ~~Test windows high contrast mode https://developer.paciellogroup.com/blog/2016/12/windows-high-contrast-mode-the-limited-utility-of-ms-high-contrast/ - check icon buttons and checkboxes and search in particular. Raised as https://github.com/infor-design/enterprise/issues/1615~~
- [x] Confirm data on this page https://design.infor.com/resources/section-508-support and change it to use WCAG 2.1 guidlines and steps instead
- [x]  ~~Test out Zoomtext~~
- [x]  ~~Test out Dragon for Windows~~
- [x]  Test out zooming for Mac & iOS
- [x]  Test reading comprehension when all styles are disabled.
- [x] Full round of decided screen reader testing (QA and Dev)
- [x] Get Level Access and Landmark to do another round of more testing
