### ISSUE TITLE
Add new features to Ng for v4.17.0

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1760]
**Is your feature request related to a problem? Please describe.**

This will be a running list of changes that will need to be added in a future branch to match changes in 4.17.x. Will fill this in when i review the release log on beta of 4.17

- [ ] #1552 and #402 - Because of the way that languages work now will need to update this code https://github.com/infor-design/enterprise-ng/blob/master/src/app/locale-initializer/locale-initializer.service.ts#L58
- [ ] #1021 add beforerowactivated event https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L6669
- [ ] #592 Add new methods to Locale types (setLanguage, extendTranslations, defaultLocales, defaultLocales, supportedLocales)

**Comment by tmcconechy** [comment]
Created in the wrong place should be this: https://github.com/infor-design/enterprise-ng/issues/387
