### ISSUE TITLE
Uplift: Full Component Test Results

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2289]
**Describe the bug**
Testing each component A-Z and reporting some issues. Listed in short form. We will divide these up.

**Critical**
- [x] [Tabs Module](http://4190-beta1-enterprise.demo.design.infor.com/components/tabs-module/example-app-menu-button.html?theme=uplift) - icons and text not aligned, also the "more button" seems to not work ([PR#2306](https://github.com/infor-design/enterprise/pull/2306))
- [x] [Bar (Charts) Example](http://localhost:4000/components/bar/example-index.html?theme=uplift) - needs adjustment for larger text (all charts) ([PR#2310](https://github.com/infor-design/enterprise/pull/2310))
- [x] [Editor Example](http://4190-beta1-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift) - Select the first paragraph and hit H3. H3/H4 line height is being specified and is incorrect for the font size. ([PR#2306](https://github.com/infor-design/enterprise/pull/2306))
- [x] [Header Example](http://4190-beta1-enterprise.demo.design.infor.com/components/header/test-header-gauntlet.html?theme=uplift) - the search icon sits a little low and all the checkboxes the text is a little low
- [x] [Datagrid Example](http://localhost:4000/components/datagrid/example-filter.html?theme=uplift&variant=dark) - filter invisible

**High**
- [x] [Checkboxes Example](http://localhost:4000/components/checkboxes/example-index.html?theme=uplift) - checkbox check and partial - is too low (1px) (chrome)
- [x] [Monthview](http://4190-beta1-enterprise.demo.design.infor.com/components/monthview/example-index.html?theme=uplift) - the text in the non current month is not different weight ([PR#2309](https://github.com/infor-design/enterprise/pull/2309))

**Other**
- [x] [Accordion Example](http://localhost:4000/components/accordion/example-accordion-panels.html?theme=uplift) - the +/- icon in Education is offset - ([PR#2295](https://github.com/infor-design/enterprise/pull/2295))
- [x] [Button example](http://localhost:4000/components/button/example-index.html?theme=uplift) - buttons not fixed yet icons down a bit too much
- [x] [Counts Example](http://localhost:4000/components/counts/example-index.html) - broken recently / has an extra underline- In Edge the H3 and H4 icons are cut off
- [x] [Datagrid Example](http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift) - filter row icons has become unaligned again
- [x] [Header Hero](http://4190-beta1-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=uplift) - The text color is wrong on the hero
- [x] [Paging Example](http://localhost:4000/components/blockgrid/example-paging.html?theme=uplift)- page selector menu button alignment 

**Version**

- ids-enterprise: 4.19.0

**Screenshots**
 n/a

**Platform**
- all

**Additional context**
n/a

**Comment by clepore** [comment]
The rest of the list is continued [here (2318)](https://github.com/infor-design/enterprise/issues/2318).

**Comment by brianjuan** [comment]
http://4190-beta2-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html?theme=uplift
There still alignment issue on the page selector, page number position is too low.
<img width="648" alt="Screen Shot 2019-06-06 at 6 00 57 PM" src="https://user-images.githubusercontent.com/39508864/59024818-50415e80-8885-11e9-8087-477088688299.png">

http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift
Filter field on Qty column is closer to Column header compared to other columns, making it look unaligned
<img width="511" alt="Screen Shot 2019-06-06 at 6 03 54 PM" src="https://user-images.githubusercontent.com/39508864/59024995-bb8b3080-8885-11e9-87a5-0d37b320949c.png">

http://4190-beta2-enterprise.demo.design.infor.com/components/header/test-header-gauntlet.html?theme=uplift
Misalignment on text and checkbox, text is a bit too low.
<img width="302" alt="Screen Shot 2019-06-06 at 6 08 01 PM" src="https://user-images.githubusercontent.com/39508864/59025225-4704c180-8886-11e9-88f3-e17c15d1348a.png">

**Comment by tmcconechy** [comment]
@brianjuan moving this to down these issues have been reported on https://github.com/infor-design/enterprise/issues/2318 and one on https://github.com/infor-design/enterprise/issues/2212?email_source=notifications&email_token=AAGGZS5FYNZWIFPGJROUIYDPZCNCPA5CNFSM4HOPGRNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXBYGOA#issuecomment-499352376 we didnt have time for everything here.
