### ISSUE TITLE
Application Menu: Uplift Menu | Design QA

### ISSUE THREAD

**Issue by kevinwhitedesign** [infor-design/enterprise#2925]
**Is your feature request related to a problem? Please describe.**
Yes, related to issue https://github.com/infor-design/enterprise/pull/2861 needs continued design QA

**Describe the solution you'd like**
Basically @EdwardCoyle & I had a back and forth seen here:
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538058493
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538061769
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538112804

This is an addition upon that here are the design revisions:

- [ ] The menu is looking at things from a background perspective that is light to dark (bg is light, a hover state is darker) this should be flipped. It should start dark to light because the other headers and page elements will be lighter.

- [x] Menu background — background: #252429;

- [x] Hover Menu Item — background #323036;
border-radius: 6px; 
TYPE
font-family: SourceSansPro-Regular;
font-size: 16px;
color: #FFFFFF;
>>> 2ND LVL & BEYOND <<<
font-family: SourceSansPro-Regular;
font-size: 14px;
color: #FFFFFF;

- [x] Selected Menu Item — background: #5C5861;
TYPE
font-family: SourceSansPro-SemiBold;
font-size: 16px;
color: #FFFFFF;
>>> 2ND LVL & BEYOND <<<
font-family: SourceSansPro-Regular;
font-size: 14px;
color: #FFFFFF;

- [x] Expanded Menu Item (first level only) — background: #000000;
TYPE
font-family: SourceSansPro-SemiBold;
font-size: 16px;
color: #FFFFFF;

- [ ] On the option with the 'expanded menu item level w/ background', lets make the shape edge to edge (and remove the rounded corners) https://www.dropbox.com/s/mqzwcthvnhlzikp/Screenshot%202019-10-08%2016.32.47.png?dl=0 

- [ ] The option 'expanded menu item level WITHOUT background should be developed: https://www.dropbox.com/s/v1wi6df2gvq2w10/Screenshot%202019-10-08%2016.35.31.png?dl=0

- [ ]Focus state hiding should be double checked

- [ ] I will need to provide the color states for other themes as well. So that the menu can be accessible across.

**Describe alternatives you've considered**
Opacity. I see it's value in that you can set it and forget it. In this case, we're working on a component that can be themed and opacity would work well across. Concerns around accessibility, but as long as we test against that it could still work. This could be promising.

**Additional context**
Updated designs:
![IDS_ApplicationMenu_superExpandedNavItems_alt](https://user-images.githubusercontent.com/6478704/66432481-2a22fb00-e9ec-11e9-9409-a597c81f84f3.png)
![IDS_ApplicationMenu_superExpandedNavItems](https://user-images.githubusercontent.com/6478704/66432482-2a22fb00-e9ec-11e9-8f74-83fc98140364.png)
![IDS_ApplicationMenu_expandedNavItems](https://user-images.githubusercontent.com/6478704/66432483-2a22fb00-e9ec-11e9-8c46-91179b2b19b5.png)
![IDS_ApplicationMenu_WithoutIcons](https://user-images.githubusercontent.com/6478704/66432484-2abb9180-e9ec-11e9-8646-0bff37b2df1f.png)
![IDS_ApplicationMenu_WithIcons](https://user-images.githubusercontent.com/6478704/66432485-2abb9180-e9ec-11e9-8c0f-fc91f2dfa664.png)
![original](https://user-images.githubusercontent.com/6478704/66432486-2abb9180-e9ec-11e9-96ef-ae1b7afcdfde.png)

**Comment by kevinwhitedesign** [comment]
CC @benfenton and @elizabethhartley

**Comment by EdwardCoyle** [comment]
@kevinwhitedesign per these:

> On the option with the 'expanded menu item level w/ background', lets make the shape edge to edge (and remove the rounded corners)
> https://www.dropbox.com/s/mqzwcthvnhlzikp/Screenshot%202019-10-08%2016.32.47.png?dl=0

 > The option 'expanded menu item level WITHOUT background should be developed: > https://www.dropbox.com/s/v1wi6df2gvq2w10/Screenshot%202019-10-08%2016.35.31.png?dl=0

Is there a use case for "not having a background" versus "having a background" in the nested navigation areas?  We don't currently have two options for this -- the nested area in the original Soho theme has a distinct background color.

----

As an aside, I would probably not base any design revisions on what's currently in HCM, since we already did a handful of revisions in #2681.  We should probably be basing design revisions against what's in IDS Enterprise's `master` branch:  http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift

For a full list off application menu examples, check out http://master-enterprise.demo.design.infor.com/components/applicationmenu/list

**Comment by kevinwhitedesign** [comment]
WOah! Apologies for the delay here. I'm a GitHub Noob lol

The use case for that was for separation between the 1st level menu and sub menus. This can be solved with the indentation and vertical spacing (at the bottom of an expanded section) alone rather than background color to my point.

To your second section, I hope I'm basing things of IDS! I think I just provided an old IDS vs HCM implementation example on accident. The link you shared is what I remembered looking at while compiling these updates.

**Comment by elizabethhartley** [comment]
I think we need to step back on this for a sec as we QA the color palette — I'm also concerned about a full color palette vs. just base colors and tints and shades.

**Comment by tmcconechy** [comment]
We did apply the changes to the hierarchies already. But if we need to tweak something we can.
This pattern is a bit tricky when it comes to colors because its done with code / percentages of the base color as it can be any color.

**Comment by jbrcna** [comment]
QA **FAILED**
the icons seem fine. However, I found some inconsistencies while using the search function. please see screenshot below

Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=light

![image](https://user-images.githubusercontent.com/56722184/70791176-8bdb5900-1dd1-11ea-9f4b-ee5c630d0531.png)

![image](https://user-images.githubusercontent.com/56722184/70791330-e1176a80-1dd1-11ea-9d4e-a522018c5f78.png)

**Comment by janahintal** [comment]
Hi @tmcconechy , notice that the search filter is not working as expected after filtering to Profile.

Steps:
1. Go to http://4240-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=light 
2. In the search field, type 'Profile' then **press Enter**
3. Notice that the Profile is not filtered

**Comment by jbrcna** [comment]
QA **Failed**
The layout issue indicated in the above screenshot (_[not centered & extra line](https://github.com/infor-design/enterprise/issues/2925#issuecomment-565403265)_)was now resolved. However, when you search for a sub-item it doesn't show.

Verified in http://4240-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/56722184/71241226-124de880-2346-11ea-8bfc-01da968b94ed.png)

**Comment by tmcconechy** [comment]
@deep7102 @EdwardCoyle Was this the issue you discussed that we said we would make a new issue for?

**Comment by EdwardCoyle** [comment]
@tmcconechy yes, I will raise an issue to fix this in the next release.  This isn't something we're going to be able to address by code cutoff.

**Comment by tmcconechy** [comment]
Sounds good. Will just move this to done and we can address later.
