### ISSUE TITLE
Testing: Add automation ID functionality

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4498]
**Is your feature request related to a problem or use case? Please describe.**

This feature is to add the automation ID functionality (attributes) setting to all components. The issue is broke into sections for each person. You can do one or several PR's against this ticket and feel free to swap the components out if the breakdown makes more sense for one the other is doing. Rough work is:

- add attributes setting js doc
- add utils.addAttributes
- in the build or place where the modal is generated add an addAttributes for the component root
- and one for each thing that is clickable that is "appened" for example in the toast for `btn-close`
- add readme.md section for testability with same text and noting what's appended for the component
- an e2e test

Can look at modal, message, pager, toast, colorpicker now as completed. Example for color picker https://github.com/infor-design/enterprise/pull/4492

**Component Assignments Checklist**

**Eric**
- [x] Busyindicator
- [x] Circlepager
- [x] Emptymessage
- [x] Error Page
- [x] Expandablearea
- [x] Notification
- [x] Rating
- [x] Slider
- [x] Spinbox
- [x] Splitter
- [x] Switch
- [x] Textarea
- [x] Timeline
- [x] Timepicker
- [x] Signin

**John**
- [x] Autocomplete
- [x] Contextmenu
- [x] Field Filter
- [x] Field Options
- [x] Fieldset
- [x] Fileupload
- [x] Fileupload Advanced
- [x] Dropdown
- [x] Multiselect
- [x] Popdown
- [x] Popover (#4551)
- [x] Popupmenu (#4544)
- [x] Searchfield
- [x] Toolbarsearchfield

**Ed**
- [x] Accordion (ids just go on the elements?) (#4514)
- [x] Applicationmenu (ids just go on the elements?) (#4514)
- [x] Breadcrumb (#4514)
- [x] Button (#4544)
- [x] Input (check cases it may not be needed?) (#4529)
- [x] Listview (#4529)
- [x] Lookup
- [x] Tabs (#4518)
- [x] Tabs Header (#4518)
- [x] Tabs Module (#4518)
- [x] Tabs Multi (#4518)
- [x] Tabs Vertical (#4518)
- [x] Toolbar Flex (#4544)
- [x] Toolbar (#4558)
- [x] Tooltip (#4551)

**Tim** 
- [x] About
- [x] Contextualactionpanel
- [x] Donut
- [x] Pie
- [x] Calendar
- [x] Calendar Toolbar
- [x] Week View
- [x] Monthview
- [x] Radios
- [x] Progress
- [x] Treemap
- [x] Datepicker
- [x] Wizard
- [x] Datagrid

**Deepak** 
- [x] Area (#4511)
- [x] Bar (#4516)
- [x] Bar Grouped (#4516)
- [x] Bar Stacked (#4516)
- [x] Blockgrid (#4549)
- [x] Bubble (#4511)
- [x] Bullet (#4531)
- [x] Column (#4516)
- [x] Column Grouped (#4516)
- [x] Column Stacked (#4516)
- [x] Completion Chart (#4537)
- [x] Editor (#4561)
- [x] Hierarchy (#4561)
- [x] Line (#4511)
- [x] Listbuilder (#4549)
- [x] Positive Negative (#4516)
- [x] Processindicator (#4564)
- [x] Radar (#4525)
- [x] Scatterplot (#4511)
- [x] Sparkline (#4525)
- [x] Stepchart (#4531)
- [x] Swaplist (#4549)
- [x] Targeted Achievement (#4537)
- [x] Tree (#4564)

**Done** 
- [x] Colorpicker
- [x] Message
- [x] Modal
- [x] Pager
- [x] Toast
- [x] Toolbar (deprecated for toolbar flex)

**Not Needed** 

For these ones it is presumed that you can add a `id="my-id"` or `data-automation-id="something"` direcly in the DOM markup and nothing is "generated" so it does not need this feature. I.E. something flat and css only.

- [x] Alerts
- [x] Badges
- [x] Checkboxes
- [x] Header
- [x] Homepage 
- [x] Hyperlinks
- [x] Icons 
- [x] Images 
- [x] Masthead
- [x] Skiplink
- [x] Tag

**Comment by tmcconechy** [comment]
For QA these are at the moment on https://master-enterprise.demo.design.infor.com/components/list most of the examples are on the example-index.

In a few days this will be on a beta link and in the future this will be on a release link.

**Comment by tmcconechy** [comment]
All components are done. Nice job fellas

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
