### ISSUE TITLE
Datagrid:  Request to allow a custom icon for the trigger icon of a filterable column

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4527]
**Describe the feature**
Asking for a way to specify a custom icon for the trigger icon of a filterable column.

**Additional context**
In Landmark working on filtering a code block column.  Currently setting the column to use the filter type of 'lookup'. The current lookup icon will be confusing for landmark users since filtering a code block column we will not be opening a select list dialog.

Additionally when specifying column editorOptions of editable: false, the css background needs to change.

```
 Code snippet for setting filtering of a code block column:
    column.filterConditions =  [ 'contain' ];
    column.filterType = 'lookup';
    column.editorOptions = {
        editable: false,
        click: codeBlockFilterClickFunction
   };
```

**Tasks**

- [x] Add a setting to lookup for any icon
- [x] Allow readonly inputs on the filter row and style them as needed
- [x] Style the clearable x so it is positioned ok

**Comment by claudenbach** [comment]
![FilteringCodeBlock](https://user-images.githubusercontent.com/39804038/96884057-b4e36600-1446-11eb-8228-4753922d6aac.gif)

**Comment by claudenbach** [comment]
Here's what I see when using the clearable=true option.

![FilterClearable](https://user-images.githubusercontent.com/39804038/97355512-ff108100-1864-11eb-9d2b-5dc0f5dd8759.gif)

**Comment by tmcconechy** [comment]
ok makes sense - looks like the position is off when in filter row since no one ever tried this. Added a task

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/lookup/example-icon
![image](https://user-images.githubusercontent.com/56722184/98803356-940f9e80-244f-11eb-8f68-700777eb3ed1.png)
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter.html
![image](https://user-images.githubusercontent.com/56722184/98803533-e3ee6580-244f-11eb-82ab-663f48ed12f4.png)
