### ISSUE TITLE
Testing: Add page to design.infor.com

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4556]
**Describe the task**
Need to add more contents on testing/test automation

**Tasks**

- [x] Fix link on current page
- [x] Add some contents from doc
- [x] idea around automation ids
- [x] IDs and automation testing
- [x] Around the concept - fx datagrid

**Comment by tmcconechy** [comment]
cc @lucacolumbu

**Comment by tmcconechy** [comment]
Added a page to https://staging.design.infor.com/resources/application-automation-testing for review once we gather feedback will move live.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
