### ISSUE TITLE
General: Make 'Dirty' Tracking a State 

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5259]
**Is your feature request related to a problem or use case? Please describe.**
Transferring this ticket from IDS Design Jira: https://jira.infor.com/browse/UXD-2549 

**Describe the solution you'd like**
Right now, dirty is represented as a component. Meanwhile, it's actually a ui state of several components.

How to resolve:

- [x] Add Dirty as a state within design components in Figma Library (completed) 
- [x] Remove this frame/artboard from [Figma ](https://master-enterprise.demo.design.infor.com/components/trackdirty/example-index.html)
- [ ] Transfer dirty states from this individual dirty [demo site](https://main-enterprise.demo.design.infor.com/components/trackdirty/example-index.html) page to component pages that are missing dirty states:
- [ ] [Multiselect](https://master-enterprise.demo.design.infor.com/components/trackdirty/example-index.html) component is missing dirty state from what I see
- [ ] Text area? Can't find a page for this
- [ ] Dropdown is missing a dirty state within it's page from what I see

**Additional context**
This task completion helps Designers get to -> better organization/taxonomy of components.

Thanks!

**Comment by tmcconechy** [comment]
I dont really understand this issue if you look at https://main-enterprise.demo.design.infor.com/components/trackdirty/example-index.html

1. I see text area as an example
2. i see dropdown as an example
3. i see multiselect as an example

I also dont understand "making it a state" as it is a state?

**Comment by tmcconechy** [comment]
Closing in favor of https://github.com/infor-design/enterprise/issues/5319
