### ISSUE TITLE
Notification Badge: Create new component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5344]
**Is your feature request related to a problem or use case? Please describe.**

WFM and others have needed a dot to indicate there are new "events" inside some object.

**Describe the solution you'd like**
Code this design https://www.figma.com/file/v4k6FYW7RokctgnU9MrZuK/IDS-Notification-Badge?version-id=929134509&node-id=0%3A1&viewport=318%2C455%2C0.061992693692445755 for the high priority items only

**Tasks to Do**
- [x] Add classes that can be added to icons
- [x] One set of classes for position (upper-left, upper-right, lower-left, lower-right)
- [x] One set of classes for dot color (status-01 - status-06) check if these colors need adding or exist
- [x] Show an example of badge placement section
- [x] Add the new settings to activate the classes to Angular wrappers
- [ ] Add this to the Web component repo with two settings on the ids-icon fx (notification-badge-color, notification-badge-position) or just badge-color...? And add one example of an icon in each 4 positions and 6 colors. (10 total)
- [ ] Test out the scenarios in the design doc

**Additional context**
https://jira.infor.com/browse/UXD-2122

**Comment by jbrcna** [comment]
QA Passed
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/notification-badge/example-badge-placement.html
![image](https://user-images.githubusercontent.com/56722184/127618209-1c097fb5-aab4-421d-83b8-ef98ce1a5b5d.png)

 id's and automation id's are verified. logs can be seen here [log.html.zip](https://github.com/infor-design/enterprise/files/6907442/log.html.zip)

**Comment by CindyMercadoReyes** [comment]
BDD attached. 
[BDDStory_github5344.docx](https://github.com/infor-design/enterprise/files/6963313/BDDStory_github5344.docx)
