### ISSUE TITLE
TimePicker: Add option to limit hours

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5880]
**Describe the Feature**
There are use cases where we need the user to pick within a defined range:
ex. Pick a time during your scheduled work hour (8am-4pm). This just puts less hours in the list..

Design: https://www.figma.com/file/b4FR4NZg5yUHoEj2scWjPM/Timepicker?node-id=4%3A2

**Tasks**

- [ ] Add a setting `hourRange: [0, 24]`
- [ ] Add an example
- [ ] Add a test
- [ ] Add a test and the same setting to the web component version

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tjamesallen15** [comment]
Hello @tmcconechy, when I clicked the design link it says file not found. 
![image](https://user-images.githubusercontent.com/34049950/144777624-91ce73b3-79e8-4677-96f2-7dbe7534c25f.png)

**Comment by tmcconechy** [comment]
I asked @kevinwhitedesign should be good now 👍🏻

**Comment by tjamesallen15** [comment]
> I asked @kevinwhitedesign should be good now 👍🏻

Just checked the link. Still the same issue.

**Comment by CindyMercadoReyes** [comment]
BDD attached.
[BDDStory_github5880.docx](https://github.com/infor-design/enterprise/files/7737717/BDDStory_github5880.docx)

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.59.0-dev.
verified in https://main-enterprise.demo.design.infor.com/components/timepicker/example-hour-range.html
![image](https://user-images.githubusercontent.com/56722184/146724770-b509f019-c58d-4c38-a3a8-9167eb9e0050.png)

![image](https://user-images.githubusercontent.com/56722184/146724780-f0131023-eb4a-4efb-abf0-c4da1b5fd034.png)
