### ISSUE TITLE
MonthView: In page version enhancements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5881]
**Describe the Feature**
Need to add a few new features to https://main-enterprise.demo.design.infor.com/components/monthview/test-inpage-variations.html as listed and noted in the designs:

https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/IDS-Calendar?node-id=313%3A340

**Tasks**
- [ ] Add a setting to monthview/calendar toolbar that lets you set a format for the date on the header fx: `headerDateFormat: 'MMM dd, yyy'`  or `headerDateFormat: 'month'` as it takes from the locale  https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/bg-BG.js#L21-L22
- [ ] Make a setting/method to make https://main-enterprise.demo.design.infor.com/components/monthview/example-inpage.html be expanded down by default or not
- [ ] Check hitpoints and padding are correct for arrow buttons
- [ ] Add an option/example for an extra button

**Additional context**
https://jira.infor.com/browse/UXD-3636
