### ISSUE TITLE
Fix sporadically failing e2e tests

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#753]
**Is your feature request related to a problem? Please describe.**
We need to ensure that there are no sporadic failures of tests during our builds.  Some progress was made on this in #720, but there are still occasional test failures.  The reasons for these failures are unclear.

**Describe the solution you'd like**
- [x] Review all current testing documentation
- [ ] Understand what causes the BrowserStack tests to fail sporadically
- [ ] Document a list of anti-patterns to avoid when writing tests (in docs/TESTING.md)
- [ ] Fix any anti-patterns existing in current tests, while maintaining the goals of each test
- [ ] Fix all skipped tests
- [ ] Review/improve Visual Regression testing process (can be we build baseline images for Axe tests without needing the docker setup?)

**On Going List of suddenly sporadically failing tests that need fixing:**

- [ ] `Datagrid contextmenu tests Should show context menu` - reported on #783
- [x] `Lookup custom button tests should display with custom buttons` - reported on #795 
- [ ] `Should select tab, and focus` - Reported by @clepore on [this build](https://travis-ci.com/infor-design/enterprise/jobs/146428511#L2207)
- [x] `Tabs ajax as href tests Should be able to activate href tabs` - reported on #855 failing [this build](https://travis-ci.com/infor-design/enterprise/jobs/148169340#L2398)
- [x] `Tabs vertical click test-nested-regular-tabs tests Should open nested 2nd tab on first vertical tab (page 1), on click` - reported on #858 failing [this build](https://travis-ci.com/infor-design/enterprise/jobs/148381275#L2345)

**Comment by EdwardCoyle** [comment]
@tmcconechy this one's going to be mostly me, but I've assigned you for now so I can get some debriefing on what you know about the BrowserStack infrastructure.  Let's setup a meeting when you get back from vacation.

**Comment by tmcconechy** [comment]
Ok, just setup a call - my calendar is updated.

**Comment by EdwardCoyle** [comment]
**List of suddenly sporadically failing tests that need fixing:**

- [ ] `Datagrid contextmenu tests Should show context menu' - reported on #783

**Comment by tmcconechy** [comment]
We good on this for now you think @EdwardCoyle ?

**Comment by tmcconechy** [comment]
I think we can probably close this for now. Feel free to reopen if you think im wrong.
Things seem more stable now after many revisions
