### ISSUE TITLE
General: Fix language support in font-face.css and demo app

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8671]
**Describe the bug**

Need to add all the custom language fonts to the demo app. 

**Tasks**

- [ ] See if approved with legal
- [ ] for each of the font urls open the link in the browser
- [ ] download each file
- [ ] add the file to the font-face.css like the existing ones based on whats in the file (you only need the ones for the language in question)
- [ ] test all locales

**Font urls**

https://fonts.googleapis.com/css?family=Mada:300,400,600&amp;display=swap&amp;subset=hebrew

https://fonts.googleapis.com/css?family=Assistant:300,400,600&amp;display=swap&amp;subset=hebrew

https://fonts.googleapis.com/css?family=Noto+Sans:300,400,700&amp;display=swap&amp;subset=devanagari
        
https://fonts.googleapis.com/css?family=Noto+Sans+JP:300,400,700&amp;display=swap&amp;subset=japanese
        
https://fonts.googleapis.com/css?family=Noto+Sans+KR:300,400,700&amp;display=swap&amp;subset=korean
        
https://fonts.googleapis.com/css?family=Sarabun:300,400,600&amp;display=swap&amp;subset=thai
        
https://fonts.googleapis.com/css?family=Noto+Sans+SC:300,400,700&amp;display=swap&amp;subset=chinese-simplified
       
**Font Matrix**
```
$cultures-font-family: (
  'ar-EG': ('Mada', 'Source Sans Pro', 'arial', sans-serif),
  'ar-SA': ('Mada', 'Source Sans Pro', 'arial', sans-serif),
  'he-IL': ('Assistant', 'Source Sans Pro', 'arial', sans-serif),
  'hi-IN': ('Noto Sans', 'Source Sans Pro', 'arial', sans-serif),
  'ja-JP': ('Noto Sans JP', 'Source Sans Pro', 'arial', sans-serif),
  'ko-KR': ('Noto Sans KR', 'Source Sans Pro', 'arial', sans-serif),
  'th-TH': ('Noto Sans Thai', 'Source Sans Pro', 'arial', sans-serif),
  'zh-CN': ('Noto Sans SC', 'Source Sans Pro', 'arial', sans-serif),
  'zh-TW': ('Noto Sans TC', 'Source Sans Pro', 'arial', sans-serif),
  'zh-Hans': ('Noto Sans SC', 'Source Sans Pro', 'arial', sans-serif),
  'zh-Hant': ('Noto Sans TC', 'Source Sans Pro', 'arial', sans-serif)
);
```

**To Test**

1. go to https://main-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=zh-TW changing the url as above in the matrix
2. inspect the text and look on the rendered fonts tab that the correct one loaded

<img width="946" alt="Screenshot 2024-05-02 at 1 20 12 PM" src="https://github.com/infor-design/enterprise/assets/814283/6bc560f2-bc68-42e1-9c96-63db7c84a3ac">
